global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'text2sql-app'
    static_configs:
      - targets: ['dbgpt-web:5000']
    metrics_path: '/metrics'
    
  - job_name: 'llm-proxy'
    static_configs:
      - targets: ['llm-proxy:8080']
    metrics_path: '/metrics'
    
  - job_name: 'promptx-exporter'
    static_configs:
      - targets: ['promptx-exporter:9101']
    
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
      
  - job_name: 'chromadb'
    static_configs:
      - targets: ['chromadb:8000']
    metrics_path: '/metrics'
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
