version: '3.8'

networks:
  text2sql-net:
    driver: bridge

volumes:
  postgres-data:
  chroma-data:
  prometheus-data:
  grafana-data:
  registry-data:

services:
  # 私有Registry
  registry:
    image: docker.io/library/registry:2
    container_name: text2sql-registry
    ports:
      - "5000:5000"
    volumes:
      - registry-data:/var/lib/registry
    networks:
      - text2sql-net
    restart: unless-stopped

  # 数据库服务
  postgres:
    image: docker.io/library/postgres:15-alpine
    container_name: text2sql-db
    environment:
      POSTGRES_USER: text2sql
      POSTGRES_PASSWORD: secure_password_2025
      POSTGRES_DB: text2sql_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./config/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - text2sql-net
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U text2sql"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # 向量数据库
  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: text2sql-vec
    volumes:
      - chroma-data:/chroma/chroma
    networks:
      - text2sql-net
    ports:
      - "8000:8000"
    environment:
      IS_PERSISTENT: "TRUE"
      PERSIST_DIRECTORY: "/chroma/chroma"
      ANONYMIZED_TELEMETRY: "FALSE"
    restart: unless-stopped

  # LLM代理服务
  llm-proxy:
    build:
      context: ./docker/llm-proxy
      dockerfile: Dockerfile
    container_name: text2sql-llm-proxy
    environment:
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-your-api-key-here}
      RATE_LIMIT_RPM: 60
      RATE_LIMIT_TPM: 100000
    networks:
      - text2sql-net
    ports:
      - "8080:8080"
    volumes:
      - ./config/llm-proxy:/app/config:ro
    restart: unless-stopped

  # DB-GPT主服务
  dbgpt-web:
    build:
      context: ./db-gpt
      dockerfile: Dockerfile
    container_name: text2sql-app
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: text2sql
      DB_PASSWORD: secure_password_2025
      DB_NAME: text2sql_db
      VECTOR_DB_URL: http://chromadb:8000
      LLM_PROXY_URL: http://llm-proxy:8080
    networks:
      - text2sql-net
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
      chromadb:
        condition: service_started
      llm-proxy:
        condition: service_started
    volumes:
      - ./config/dbgpt:/app/config:ro
      - ./promptx:/app/promptx:ro
      - ./logs:/app/logs
    restart: unless-stopped

  # Prometheus监控
  prometheus:
    image: docker.io/prom/prometheus:latest
    container_name: text2sql-prometheus
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    networks:
      - text2sql-net
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    restart: unless-stopped

  # Grafana可视化
  grafana:
    image: docker.io/grafana/grafana:latest
    container_name: text2sql-grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin123
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./config/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./config/grafana/datasources:/etc/grafana/provisioning/datasources:ro
    networks:
      - text2sql-net
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: unless-stopped

  # PromptX MCP导出器（新增）
  promptx-exporter:
    image: docker.io/library/python:3.10-slim
    container_name: text2sql-promptx-exporter
    command: python /app/exporter.py
    volumes:
      - ./monitoring/promptx-exporter:/app:ro
      - ./promptx/memory:/data/memory:ro
    networks:
      - text2sql-net
    ports:
      - "9101:9101"
    environment:
      EXPORTER_PORT: 9101
      MEMORY_PATH: /data/memory
    restart: unless-stopped
